version: '3.1'

services:

  nginx:
    image: nginx:latest
    volumes:
      - ./code:/code
      - ./site.conf:/etc/nginx/conf.d/site.conf
    ports:
      - 81:80
    links:
      - php

  php:
    image: php:7-fpm
    volumes:
      - ./code:/code